"""The cost of determinism — FR-A-04.

This is ATTEST's most valuable single output. vLLM publishes improvements to the
batch-invariant path *relative to its own earlier self*; what nobody has published
is the price of invariance versus default, which is the number a bank actually
needs before it can decide whether reproducibility is affordable.

Which makes the reporting discipline matter more than usual:

* Every figure carries a **bootstrap confidence interval**. A bare ratio invites
  the reader to treat noise as signal.
* Latency percentiles are reported, not just means. TTFT distributions are
  long-tailed; a mean hides exactly the behaviour an operator cares about.
* A comparison across **different hardware or different sessions is refused**.
  Throughput measured on two machines is not a delta, it is two numbers.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from typing import Any

import numpy as np
from numpy.typing import NDArray


class IncomparableMeasurements(ValueError):
    """Refusal to compare measurements that did not share their conditions."""


@dataclass(frozen=True)
class LatencySummary:
    n: int
    mean: float
    p50: float
    p95: float
    p99: float

    def to_dict(self) -> dict[str, float | int]:
        return {"n": self.n, "mean": self.mean, "p50": self.p50, "p95": self.p95, "p99": self.p99}


def summarise_latency(samples: Sequence[float] | NDArray[np.float64]) -> LatencySummary:
    arr = np.asarray(samples, dtype=np.float64)
    if arr.size == 0:
        raise ValueError("no latency samples")
    if not np.all(np.isfinite(arr)):
        raise ValueError("latency samples contain NaN or infinity")
    if np.any(arr < 0):
        raise ValueError("negative latency is not a measurement, it is a bug")

    p50, p95, p99 = np.quantile(arr, [0.5, 0.95, 0.99])
    return LatencySummary(
        n=int(arr.size),
        mean=float(arr.mean()),
        p50=float(p50),
        p95=float(p95),
        p99=float(p99),
    )


def ratio_bootstrap_ci(
    baseline: NDArray[np.float64],
    treatment: NDArray[np.float64],
    *,
    statistic: str = "mean",
    n_resamples: int = 10_000,
    confidence: float = 0.95,
    rng_seed: int,
) -> tuple[float, float, float]:
    """Bootstrap CI for ``treatment / baseline`` of a summary statistic.

    A ratio because that is how the cost is read — "invariance costs 1.4x
    throughput" travels; "invariance costs 213 tokens per second" does not
    survive contact with different hardware.

    Resampled independently per arm, which is correct here: the two arms are
    separate engine configurations, not paired observations of one request.
    """
    base = np.asarray(baseline, dtype=np.float64)
    treat = np.asarray(treatment, dtype=np.float64)
    for name, arr in (("baseline", base), ("treatment", treat)):
        if arr.size < 2:
            raise ValueError(f"{name} needs at least 2 samples, got {arr.size}")
        if not np.all(np.isfinite(arr)):
            raise ValueError(f"{name} contains NaN or infinity")

    def stat(a: NDArray[np.float64]) -> float:
        if statistic == "mean":
            return float(a.mean())
        if statistic.startswith("p"):
            return float(np.quantile(a, int(statistic[1:]) / 100.0))
        raise ValueError(f"unknown statistic: {statistic!r}")

    base_stat = stat(base)
    if base_stat == 0:
        raise ValueError("baseline statistic is zero; a ratio would be undefined")
    point = stat(treat) / base_stat

    rng = np.random.default_rng(rng_seed)
    replicates = np.empty(n_resamples, dtype=np.float64)
    for i in range(n_resamples):
        b = stat(rng.choice(base, size=base.size, replace=True))
        t = stat(rng.choice(treat, size=treat.size, replace=True))
        replicates[i] = t / b if b != 0 else np.nan

    usable = replicates[np.isfinite(replicates)]
    alpha = 1.0 - confidence
    lo, hi = np.quantile(usable, [alpha / 2.0, 1.0 - alpha / 2.0])
    return point, float(lo), float(hi)


@dataclass(frozen=True)
class CostReport:
    """The cost-of-determinism table. Regenerated by script, never hand-edited."""

    throughput_off: LatencySummary
    throughput_on: LatencySummary
    ttft_off: LatencySummary
    ttft_on: LatencySummary
    throughput_ratio: tuple[float, float, float]
    ttft_p50_ratio: tuple[float, float, float]
    ttft_p99_ratio: tuple[float, float, float]
    seed: int
    conditions: Mapping[str, Any]

    def to_dict(self) -> dict[str, Any]:
        return {
            "throughput_off": self.throughput_off.to_dict(),
            "throughput_on": self.throughput_on.to_dict(),
            "ttft_off": self.ttft_off.to_dict(),
            "ttft_on": self.ttft_on.to_dict(),
            "throughput_ratio": list(self.throughput_ratio),
            "ttft_p50_ratio": list(self.ttft_p50_ratio),
            "ttft_p99_ratio": list(self.ttft_p99_ratio),
            "seed": self.seed,
            "conditions": dict(self.conditions),
        }

    def to_markdown(self) -> str:
        def row(label: str, ratio: tuple[float, float, float], unit: str) -> str:
            point, lo, hi = ratio
            return f"| {label} | {point:.3f}x | [{lo:.3f}, {hi:.3f}] | {unit} |"

        return "\n".join(
            [
                "| metric | invariance on / off | 95% CI | direction |",
                "|---|---|---|---|",
                row("output throughput", self.throughput_ratio, "higher is better"),
                row("TTFT p50", self.ttft_p50_ratio, "lower is better"),
                row("TTFT p99", self.ttft_p99_ratio, "lower is better"),
            ]
        )

    def headline(self) -> str:
        point, lo, hi = self.throughput_ratio
        direction = "costs" if point < 1.0 else "gains"
        pct = abs(1.0 - point) * 100
        return (
            f"batch invariance {direction} {pct:.1f}% of output throughput "
            f"(ratio {point:.3f}, 95% CI [{lo:.3f}, {hi:.3f}], n={self.throughput_on.n})"
        )


def _require_same_conditions(off: Mapping[str, Any], on: Mapping[str, Any]) -> dict[str, Any]:
    """Both arms must share hardware, model and session.

    Throughput measured on two machines is not a delta, it is two numbers, and
    presenting it as a cost would be the most damaging kind of wrong — plausible.
    """
    keys = ("gpu", "model", "run_id", "max_tokens", "concurrency")
    mismatched = {k: (off.get(k), on.get(k)) for k in keys if off.get(k) != on.get(k)}
    if mismatched:
        detail = "; ".join(f"{k}: off={a!r} on={b!r}" for k, (a, b) in mismatched.items())
        raise IncomparableMeasurements(
            f"refusing to compare arms measured under different conditions — {detail}"
        )
    return {k: off.get(k) for k in keys}


def build_cost_report(
    *,
    throughput_off: Sequence[float],
    throughput_on: Sequence[float],
    ttft_off: Sequence[float],
    ttft_on: Sequence[float],
    conditions_off: Mapping[str, Any],
    conditions_on: Mapping[str, Any],
    rng_seed: int,
    n_resamples: int = 10_000,
) -> CostReport:
    conditions = _require_same_conditions(conditions_off, conditions_on)

    off_t = np.asarray(throughput_off, dtype=np.float64)
    on_t = np.asarray(throughput_on, dtype=np.float64)
    off_l = np.asarray(ttft_off, dtype=np.float64)
    on_l = np.asarray(ttft_on, dtype=np.float64)

    return CostReport(
        throughput_off=summarise_latency(off_t),
        throughput_on=summarise_latency(on_t),
        ttft_off=summarise_latency(off_l),
        ttft_on=summarise_latency(on_l),
        throughput_ratio=ratio_bootstrap_ci(
            off_t, on_t, statistic="mean", n_resamples=n_resamples, rng_seed=rng_seed
        ),
        ttft_p50_ratio=ratio_bootstrap_ci(
            off_l, on_l, statistic="p50", n_resamples=n_resamples, rng_seed=rng_seed
        ),
        ttft_p99_ratio=ratio_bootstrap_ci(
            off_l, on_l, statistic="p99", n_resamples=n_resamples, rng_seed=rng_seed
        ),
        seed=rng_seed,
        conditions=conditions,
    )
