"""Regenerate every figure in docs/figures/ from bench/results/measurements.json.

`CLAUDE.md`: *figures are regenerated by script, never hand-edited.* So this
script is the only thing that writes them, it reads one file, and that file is
the same one `tests/test_published_numbers.py` pins the prose to. A figure and a
sentence cannot disagree without a test failing.

Plain SVG, emitted by hand. Not because a plotting library would be hard, but
because the output is then diffable text with no dependency, and a reviewer can
check that a bar is the length the number says it is. A chart in a repository
about verifiable claims should itself be verifiable.

Two files per figure, `-light.svg` and `-dark.svg`, referenced from a `<picture>`
element. The dark steps are chosen for the dark surface rather than being an
inverted copy of the light ones.

    uv run python scripts/make_figures.py
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "bench" / "results" / "measurements.json"
OUT = ROOT / "docs" / "figures"


@dataclass(frozen=True)
class Theme:
    """Colour roles. The dark column is stepped for the dark surface (see the
    reference palette), not derived by inverting the light one."""

    name: str
    surface: str
    ink: str
    ink_soft: str
    grid: str
    series1: str  # blue
    series2: str  # orange
    good: str
    bad: str

    @property
    def is_dark(self) -> bool:
        return self.name == "dark"


LIGHT = Theme(
    "light", "#fcfcfb", "#0b0b0b", "#52514e", "#dedddb", "#2a78d6", "#eb6834", "#1baf7a", "#e34948"
)
DARK = Theme(
    "dark", "#1a1a19", "#ffffff", "#c3c2b7", "#3a3a38", "#3987e5", "#d95926", "#199e70", "#e66767"
)

FONT = (
    "ui-sans-serif,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,"
    "'Helvetica Neue',Arial,sans-serif"
)
MONO = "ui-monospace,SFMono-Regular,Menlo,Consolas,monospace"


def esc(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


class Svg:
    """A tiny SVG writer. Enough for bars, rules and text; nothing more."""

    def __init__(self, width: int, height: int, theme: Theme, title: str) -> None:
        self.w, self.h, self.t = width, height, theme
        self.parts: list[str] = []
        self.title = title

    def rect(self, x: float, y: float, w: float, h: float, fill: str, rx: float = 0) -> None:
        if w <= 0 or h <= 0:
            return
        self.parts.append(
            f'<rect x="{x:.1f}" y="{y:.1f}" width="{w:.1f}" height="{h:.1f}" '
            f'rx="{rx:.1f}" fill="{fill}"/>'
        )

    def line(
        self,
        x1: float,
        y1: float,
        x2: float,
        y2: float,
        stroke: str,
        width: float = 1,
        dash: str | None = None,
    ) -> None:
        d = f' stroke-dasharray="{dash}"' if dash else ""
        self.parts.append(
            f'<line x1="{x1:.1f}" y1="{y1:.1f}" x2="{x2:.1f}" y2="{y2:.1f}" '
            f'stroke="{stroke}" stroke-width="{width}"{d}/>'
        )

    def text(
        self,
        x: float,
        y: float,
        s: str,
        *,
        size: float = 12,
        fill: str | None = None,
        anchor: str = "start",
        weight: str = "400",
        mono: bool = False,
    ) -> None:
        family = MONO if mono else FONT
        self.parts.append(
            f'<text x="{x:.1f}" y="{y:.1f}" font-family="{family}" font-size="{size}" '
            f'font-weight="{weight}" fill="{fill or self.t.ink}" '
            f'text-anchor="{anchor}">{esc(s)}</text>'
        )

    def render(self) -> str:
        body = "\n  ".join(self.parts)
        return (
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{self.w}" height="{self.h}" '
            f'viewBox="0 0 {self.w} {self.h}" role="img" aria-label="{esc(self.title)}">\n'
            f"  <title>{esc(self.title)}</title>\n"
            f'  <rect width="{self.w}" height="{self.h}" fill="{self.t.surface}"/>\n'
            f"  {body}\n</svg>\n"
        )


def write(name: str, build: Any) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for theme in (LIGHT, DARK):
        (OUT / f"{name}-{theme.name}.svg").write_text(build(theme), encoding="utf-8")
    print(f"  {name}-light.svg / {name}-dark.svg")


# --------------------------------------------------------------------------- 1


def fig_divergence(data: dict[str, Any]) -> Any:
    cells = data["divergence"]["cells"]

    def build(t: Theme) -> str:
        w, h = 720, 320
        s = Svg(w, h, t, "Distinct logprob vectors in 128 identical requests")
        left, top, bar_h, gap = 250, 74, 26, 18
        span = w - left - 90
        s.text(
            24, 30, "Batched inference is not reproducible at temperature 0", size=15, weight="600"
        )
        s.text(
            24,
            50,
            "distinct logprob vectors in 128 identical requests — lower is better",
            size=12,
            fill=t.ink_soft,
        )

        for i, c in enumerate(cells):
            y = top + i * (bar_h + gap)
            label = f"{c['engine']}, determinism {'on' if c['determinism'] else 'off'}"
            s.text(
                left - 14,
                y + bar_h * 0.72,
                label,
                size=12,
                anchor="end",
                fill=t.ink if c["determinism"] else t.ink_soft,
            )
            width = span * c["distinct"] / 34
            colour = t.series1 if c["engine"] == "vLLM" else t.series2
            s.rect(left, y, max(width, 3), bar_h, colour, rx=4)
            s.text(
                left + max(width, 3) + 10,
                y + bar_h * 0.72,
                f"{c['distinct']} of 128",
                size=12,
                weight="600",
                mono=True,
            )

        base = top + len(cells) * (bar_h + gap) + 4
        s.line(left, base, left + span, base, t.grid, 1)
        s.text(
            24,
            base + 30,
            "The two engines ran under their own defaults and schedulers.",
            size=11,
            fill=t.ink_soft,
        )
        s.text(
            24,
            base + 46,
            "Read as two measurements, not as a controlled comparison.",
            size=11,
            fill=t.ink_soft,
        )
        return s.render()

    return build


# --------------------------------------------------------------------------- 2


def fig_decomposition(data: dict[str, Any]) -> Any:
    cells = {c["id"]: c for c in data["sglang_2x2"]["cells"]}
    ratios = {r["name"]: r for r in data["sglang_2x2"]["ratios"]}

    def build(t: Theme) -> str:
        w, h = 720, 372
        s = Svg(w, h, t, "Caching x determinism, decomposed, on SGLang")
        s.text(
            24,
            30,
            "The cost of determinism, separated from the cost of losing the cache",
            size=15,
            weight="600",
        )
        s.text(
            24,
            50,
            "SGLang on an H100, mean output tokens/second, 128 trials per cell",
            size=12,
            fill=t.ink_soft,
        )

        base_y, top_y = 256, 92
        scale = (base_y - top_y) / 400.0
        groups = [("determinism off", "B", "A"), ("determinism on", "D", "C")]
        gx = [150, 430]
        bw, bgap = 76, 12

        for gi, (gname, off_id, on_id) in enumerate(groups):
            for bi, (cid, colour) in enumerate(((off_id, t.series1), (on_id, t.series2))):
                cell = cells[cid]
                x = gx[gi] + bi * (bw + bgap)
                bh = cell["tokens_per_s"] * scale
                s.rect(x, base_y - bh, bw, bh, colour, rx=4)
                s.text(
                    x + bw / 2,
                    base_y - bh - 10,
                    f"{cell['tokens_per_s']:.1f}",
                    size=12,
                    weight="600",
                    anchor="middle",
                    mono=True,
                )
                s.text(
                    x + bw / 2,
                    base_y + 18,
                    f"cell {cid}",
                    size=11,
                    anchor="middle",
                    fill=t.ink_soft,
                )
            s.text(gx[gi] + bw + bgap / 2, base_y + 38, gname, size=12, anchor="middle")

        s.line(120, base_y, w - 40, base_y, t.grid, 1)

        # Legend: two series, so a legend is always present. Placed in the
        # header band rather than over the plot, where it collided with the
        # tallest bar's direct label.
        for i, (name, colour) in enumerate((("cache off", t.series1), ("cache on", t.series2))):
            lx = w - 230 + i * 108
            s.rect(lx, 42, 10, 10, colour, rx=2)
            s.text(lx + 16, 51, name, size=11, fill=t.ink_soft)

        y = 308
        s.text(24, y, "D / B", size=12, weight="600", mono=True)
        s.text(
            90,
            y,
            f"{ratios['D / B']['value']:.3f}x",
            size=12,
            weight="600",
            mono=True,
            fill=t.series2,
        )
        s.text(160, y, "determinism alone costs 18.0%, cache held off on both sides", size=12)
        s.text(24, y + 20, "C / A", size=12, mono=True, fill=t.ink_soft)
        s.text(90, y + 20, f"{ratios['C / A']['value']:.3f}x", size=12, mono=True, fill=t.ink_soft)
        s.text(
            160,
            y + 20,
            "both together — the only comparison a vLLM-shaped experiment can make",
            size=12,
            fill=t.ink_soft,
        )
        s.text(
            24,
            y + 42,
            "The confounded number UNDERSTATES the cost here: the cache is a small "
            "penalty on this workload, not a benefit.",
            size=11,
            fill=t.ink_soft,
        )
        return s.render()

    return build


# --------------------------------------------------------------------------- 3


def _interval_panel(
    s: Svg,
    t: Theme,
    rows: list[dict[str, Any]],
    *,
    x0: float,
    x1: float,
    top: float,
    row_h: float,
    label_x: float,
    thresholds: dict[str, float],
    lo: float = 0.35,
    hi: float = 1.05,
) -> float:
    """Shared AUC-with-interval panel. One axis, chance and the bar marked."""

    def px(v: float) -> float:
        return x0 + (v - lo) / (hi - lo) * (x1 - x0)

    bottom = top + len(rows) * row_h
    for v, label, dash in (
        (thresholds["chance"], "chance 0.5", "3 3"),
        (thresholds["auc_success"], "pre-registered bar 0.75", "3 3"),
    ):
        s.line(px(v), top - 12, px(v), bottom + 4, t.grid, 1, dash=dash)
        s.text(px(v), top - 20, label, size=10, anchor="middle", fill=t.ink_soft)

    for i, r in enumerate(rows):
        y = top + i * row_h + row_h / 2
        clears = bool(r.get("clears"))
        colour = t.bad if clears else t.good
        s.text(label_x, y + 4, r["label"], size=12, anchor="end")
        ci_lo, ci_hi = r["ci"]
        # A degenerate interval still has to be visible, so it gets a minimum width.
        a, b = px(ci_lo), px(ci_hi)
        if b - a < 3:
            a, b = a - 1.5, b + 1.5
        s.rect(a, y - 4, b - a, 8, colour, rx=4)
        s.line(px(r["auc"]), y - 11, px(r["auc"]), y + 11, colour, 2)
        s.text(x1 + 14, y + 4, r["annot"], size=11, mono=True, fill=t.ink_soft)
    return bottom


def fig_frb03(data: dict[str, Any]) -> Any:
    th = data["thresholds"]
    profiles = {p["profile"]: p for p in data["frb03"]["profiles"]}

    def build(t: Theme) -> str:
        w, h = 720, 334
        s = Svg(w, h, t, "FR-B-03: the routing-index leak and its mitigation")
        s.text(
            24, 30, "The cross-tenant leak, and the mitigation closing it", size=15, weight="600"
        )
        s.text(
            24,
            50,
            "same schedule, same pre-registered rule — 40 trials per profile, n=80",
            size=12,
            fill=t.ink_soft,
        )

        rows = [
            {
                "label": "default (stock llm-d)",
                "auc": profiles["default"]["auc"],
                "ci": profiles["default"]["ci"],
                "clears": True,
                "annot": "AUC 1.0000  p=9.999e-05",
            },
            {
                "label": "hardened (tenant salt)",
                "auc": profiles["hardened"]["auc"],
                "ci": profiles["hardened"]["ci"],
                "clears": False,
                "annot": "AUC 0.5000  at chance",
            },
        ]
        bottom = _interval_panel(
            s, t, rows, x0=250, x1=520, top=112, row_h=52, label_x=236, thresholds=th
        )
        for i, (name, colour) in enumerate((("attack succeeds", t.bad), ("at chance", t.good))):
            lx = 250 + i * 130
            s.rect(lx, 62, 10, 10, colour, rx=2)
            s.text(lx + 16, 71, name, size=11, fill=t.ink_soft)
        s.text(
            24,
            bottom + 44,
            "Positive class: tenant A probing a prefix tenant B planted. Negative: a "
            "prefix nobody planted.",
            size=11,
            fill=t.ink_soft,
        )
        s.text(
            24,
            bottom + 60,
            "A CONFIRMATION oracle — the probe sends the victim's prompt verbatim, so a "
            "perfect match is by construction.",
            size=11,
            fill=t.ink_soft,
        )
        s.text(
            24,
            bottom + 76,
            "It shows an attacker who can guess a prefix gets it confirmed. It does not "
            "show unknown content can be recovered.",
            size=11,
            fill=t.ink_soft,
        )
        s.text(
            24,
            bottom + 92,
            "Both intervals are degenerate — every observation is identical — so they "
            "render as a tick. That is zero variance, not precision.",
            size=11,
            fill=t.ink_soft,
        )
        return s.render()

    return build


# --------------------------------------------------------------------------- 4


def fig_s02_power(data: dict[str, Any]) -> Any:
    th = data["thresholds"]
    runs = data["s02"]["runs"]

    def build(t: Theme) -> str:
        w, h = 720, 336
        s = Svg(w, h, t, "S-02: the interval narrowing as n grew")
        s.text(
            24,
            30,
            "Why the sample size was fixed before the run that counted",
            size=15,
            weight="600",
        )
        s.text(
            24,
            50,
            "S-02 latency channel, AUC with its 95% bootstrap interval",
            size=12,
            fill=t.ink_soft,
        )

        rows = [
            {
                "label": f"run #{r['run']}  (n={r['n']})",
                "auc": r["auc"],
                "ci": r["ci"],
                "clears": r["clears_bar"],
                "annot": f"AUC {r['auc']:.4f}  p={r['p']:.4g}",
            }
            for r in runs
        ]
        bottom = _interval_panel(
            s, t, rows, x0=250, x1=520, top=112, row_h=44, label_x=236, thresholds=th
        )
        s.text(
            24,
            bottom + 40,
            "Runs #8 and #11 both sat above chance with an interval straddling it. "
            "That is not evidence of no effect;",
            size=11,
            fill=t.ink_soft,
        )
        s.text(
            24,
            bottom + 56,
            "it is what n=62 looks like when it cannot resolve an effect of that size. "
            "n=402 was fixed in the workflow",
            size=11,
            fill=t.ink_soft,
        )
        s.text(
            24,
            bottom + 72,
            "BEFORE the run that got recorded, so the answer could not be reached by "
            "stopping when it looked convenient.",
            size=11,
            fill=t.ink_soft,
        )
        return s.render()

    return build


def main() -> int:
    data = json.loads(DATA.read_text(encoding="utf-8"))
    print(f"reading {DATA.relative_to(ROOT)}")
    write("divergence", fig_divergence(data))
    write("cost-decomposition", fig_decomposition(data))
    write("frb03-verdict", fig_frb03(data))
    write("s02-power", fig_s02_power(data))
    print(f"wrote {OUT.relative_to(ROOT)}/")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
